
Import('env')
lib_env = env.Clone()

proto_files = env.Protoc(
    [],
    "configuration.proto",
    PROTOCPYTHONOUTDIR='${SOURCE.dir}/../../manager/infinisqlmgr/protocols', 
)
sources = ['reactor.cc'] + proto_files

lib = lib_env.Library('configuration', sources)
Return('lib')
