# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='configuration.proto',
  package='infinisql.configuration',
  serialized_pb='\n\x13\x63onfiguration.proto\x12\x17infinisql.configuration\"\xf6\x01\n\x07Request\x12\x42\n\x0crequest_type\x18\x01 \x02(\x0e\x32,.infinisql.configuration.Request.RequestType\x12\x44\n\rrequest_match\x18\x02 \x02(\x0e\x32-.infinisql.configuration.Request.RequestMatch\x12\x0f\n\x07node_id\x18\x03 \x01(\x05\")\n\x0bRequestType\x12\n\n\x06STATUS\x10\x00\x12\x0e\n\nASSIGNMENT\x10\x01\"%\n\x0cRequestMatch\x12\x07\n\x03\x41LL\x10\x00\x12\x0c\n\x08SPECIFIC\x10\x01\"\xf6\x02\n\x12\x41ssignmentResponse\x12K\n\x0b\x61ssignments\x18\x01 \x03(\x0b\x32\x36.infinisql.configuration.AssignmentResponse.Assignment\x1a\x92\x02\n\nAssignment\x12R\n\trole_type\x18\x01 \x02(\x0e\x32?.infinisql.configuration.AssignmentResponse.Assignment.RoleType\x12I\n\x04role\x18\x02 \x02(\x0e\x32;.infinisql.configuration.AssignmentResponse.Assignment.Role\x12\x0f\n\x07node_id\x18\x03 \x02(\x05\"\"\n\x08RoleType\x12\n\n\x06LEADER\x10\x01\x12\n\n\x06\x42\x41\x43KUP\x10\x02\"0\n\x04Role\x12\x12\n\x0eSCHEMA_MANAGER\x10\x01\x12\x14\n\x10TOPOLOGY_MANAGER\x10\x02\"\xdc\x01\n\x0eStatusResponse\x12>\n\x06status\x18\x01 \x03(\x0b\x32..infinisql.configuration.StatusResponse.Status\x1a\x89\x01\n\x06Status\x12N\n\x0bstatus_type\x18\x01 \x02(\x0e\x32\x39.infinisql.configuration.StatusResponse.Status.StatusType\x12\x0f\n\x07node_id\x18\x02 \x02(\x05\"\x1e\n\nStatusType\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04\x44OWN\x10\x02')



_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='infinisql.configuration.Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASSIGNMENT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=215,
  serialized_end=256,
)

_REQUEST_REQUESTMATCH = _descriptor.EnumDescriptor(
  name='RequestMatch',
  full_name='infinisql.configuration.Request.RequestMatch',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIFIC', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=258,
  serialized_end=295,
)

_ASSIGNMENTRESPONSE_ASSIGNMENT_ROLETYPE = _descriptor.EnumDescriptor(
  name='RoleType',
  full_name='infinisql.configuration.AssignmentResponse.Assignment.RoleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEADER', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=588,
  serialized_end=622,
)

_ASSIGNMENTRESPONSE_ASSIGNMENT_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='infinisql.configuration.AssignmentResponse.Assignment.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCHEMA_MANAGER', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOPOLOGY_MANAGER', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=624,
  serialized_end=672,
)

_STATUSRESPONSE_STATUS_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='infinisql.configuration.StatusResponse.Status.StatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=865,
  serialized_end=895,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='infinisql.configuration.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='infinisql.configuration.Request.request_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_match', full_name='infinisql.configuration.Request.request_match', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='infinisql.configuration.Request.node_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_REQUESTTYPE,
    _REQUEST_REQUESTMATCH,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=295,
)


_ASSIGNMENTRESPONSE_ASSIGNMENT = _descriptor.Descriptor(
  name='Assignment',
  full_name='infinisql.configuration.AssignmentResponse.Assignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_type', full_name='infinisql.configuration.AssignmentResponse.Assignment.role_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='infinisql.configuration.AssignmentResponse.Assignment.role', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='infinisql.configuration.AssignmentResponse.Assignment.node_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ASSIGNMENTRESPONSE_ASSIGNMENT_ROLETYPE,
    _ASSIGNMENTRESPONSE_ASSIGNMENT_ROLE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=398,
  serialized_end=672,
)

_ASSIGNMENTRESPONSE = _descriptor.Descriptor(
  name='AssignmentResponse',
  full_name='infinisql.configuration.AssignmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assignments', full_name='infinisql.configuration.AssignmentResponse.assignments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ASSIGNMENTRESPONSE_ASSIGNMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=298,
  serialized_end=672,
)


_STATUSRESPONSE_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='infinisql.configuration.StatusResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_type', full_name='infinisql.configuration.StatusResponse.Status.status_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='infinisql.configuration.StatusResponse.Status.node_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUSRESPONSE_STATUS_STATUSTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=758,
  serialized_end=895,
)

_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='infinisql.configuration.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='infinisql.configuration.StatusResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STATUSRESPONSE_STATUS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=675,
  serialized_end=895,
)

_REQUEST.fields_by_name['request_type'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST.fields_by_name['request_match'].enum_type = _REQUEST_REQUESTMATCH
_REQUEST_REQUESTTYPE.containing_type = _REQUEST;
_REQUEST_REQUESTMATCH.containing_type = _REQUEST;
_ASSIGNMENTRESPONSE_ASSIGNMENT.fields_by_name['role_type'].enum_type = _ASSIGNMENTRESPONSE_ASSIGNMENT_ROLETYPE
_ASSIGNMENTRESPONSE_ASSIGNMENT.fields_by_name['role'].enum_type = _ASSIGNMENTRESPONSE_ASSIGNMENT_ROLE
_ASSIGNMENTRESPONSE_ASSIGNMENT.containing_type = _ASSIGNMENTRESPONSE;
_ASSIGNMENTRESPONSE_ASSIGNMENT_ROLETYPE.containing_type = _ASSIGNMENTRESPONSE_ASSIGNMENT;
_ASSIGNMENTRESPONSE_ASSIGNMENT_ROLE.containing_type = _ASSIGNMENTRESPONSE_ASSIGNMENT;
_ASSIGNMENTRESPONSE.fields_by_name['assignments'].message_type = _ASSIGNMENTRESPONSE_ASSIGNMENT
_STATUSRESPONSE_STATUS.fields_by_name['status_type'].enum_type = _STATUSRESPONSE_STATUS_STATUSTYPE
_STATUSRESPONSE_STATUS.containing_type = _STATUSRESPONSE;
_STATUSRESPONSE_STATUS_STATUSTYPE.containing_type = _STATUSRESPONSE_STATUS;
_STATUSRESPONSE.fields_by_name['status'].message_type = _STATUSRESPONSE_STATUS
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['AssignmentResponse'] = _ASSIGNMENTRESPONSE
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE

class Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:infinisql.configuration.Request)

class AssignmentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Assignment(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ASSIGNMENTRESPONSE_ASSIGNMENT

    # @@protoc_insertion_point(class_scope:infinisql.configuration.AssignmentResponse.Assignment)
  DESCRIPTOR = _ASSIGNMENTRESPONSE

  # @@protoc_insertion_point(class_scope:infinisql.configuration.AssignmentResponse)

class StatusResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Status(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _STATUSRESPONSE_STATUS

    # @@protoc_insertion_point(class_scope:infinisql.configuration.StatusResponse.Status)
  DESCRIPTOR = _STATUSRESPONSE

  # @@protoc_insertion_point(class_scope:infinisql.configuration.StatusResponse)


# @@protoc_insertion_point(module_scope)
